document.addEventListener("DOMContentLoaded", function () {
  renderMathInElement(document.body, {
    delimiters: [
      { left: "\\(", right: "\\)", display: false },
      { left: "\\[", right: "\\]", display: true },
      { left: "$", right: "$", display: false },
      { left: "$$", right: "$$", display: true }
    ],
    macros: {
      "\\a": "\\mathbf{a}",
      "\\b": "\\mathbf{b}",
      "\\c": "\\mathbf{c}",
      "\\d": "\\mathbf{d}",
      "\\e": "\\mathbf{e}",
      "\\f": "\\mathbf{f}",
      "\\g": "\\mathbf{g}",
      "\\h": "\\mathbf{h}",
      "\\i": "\\mathbf{i}",
      "\\j": "\\mathbf{j}",
      "\\k": "\\mathbf{k}",
      "\\l": "\\mathbf{l}",
      "\\m": "\\mathbf{m}",
      "\\n": "\\mathbf{n}",
      "\\o": "\\mathbf{o}",
      "\\p": "\\mathbf{p}",
      "\\q": "\\mathbf{q}",
      "\\r": "\\mathbf{r}",
      "\\s": "\\mathbf{s}",
      "\\t": "\\mathbf{t}",
      "\\u": "\\mathbf{u}",
      "\\v": "\\mathbf{v}",
      "\\w": "\\mathbf{w}",
      "\\x": "\\mathbf{x}",
      "\\y": "\\mathbf{y}",
      "\\z": "\\mathbf{z}",

      "\\A": "\\mathbf{A}",
      "\\B": "\\mathbf{B}",
      "\\C": "\\mathbf{C}",
      "\\D": "\\mathbf{D}",
      "\\E": "\\mathbf{E}",
      "\\F": "\\mathbf{F}",
      "\\G": "\\mathbf{G}",
      "\\H": "\\mathbf{H}",
      "\\I": "\\mathbf{I}",
      "\\J": "\\mathbf{J}",
      "\\K": "\\mathbf{K}",
      "\\L": "\\mathbf{L}",
      "\\M": "\\mathbf{M}",
      "\\N": "\\mathbf{N}",
      "\\O": "\\mathbf{O}",
      "\\P": "\\mathbf{P}",
      "\\Q": "\\mathbf{Q}",
      "\\R": "\\mathbf{R}",
      "\\S": "\\mathbf{S}",
      "\\T": "\\mathbf{T}",
      "\\U": "\\mathbf{U}",
      "\\V": "\\mathbf{V}",
      "\\W": "\\mathbf{W}",
      "\\X": "\\mathbf{X}",
      "\\Y": "\\mathbf{Y}",
      "\\Z": "\\mathbf{Z}",

      "\\fhat": "\\hat{f}",
      "\\shat": "\\hat{s}",
      "\\yhat": "\\hat{y}",
      "\\bfhat": "\\mathbf{\\hat{f}}",
      "\\bshat": "\\mathbf{\\hat{s}}",
      "\\byhat": "\\mathbf{\\hat{y}}",
      
      "\\rr": "\\tilde{r}",
      "\\xx": "\\tilde{x}",
      "\\yy": "\\tilde{y}",
      "\\zz": "\\tilde{z}",
      "\\brr": "\\tilde{\\mathbf{r}}",
      "\\bxx": "\\tilde{\\mathbf{x}}",
      "\\byy": "\\tilde{\\mathbf{y}}",
      "\\bzz": "\\tilde{\\mathbf{z}}",

      "\\WW": "\\tilde{\\mathbf{W}}",
      "\\XX": "\\tilde{\\mathbf{X}}",
      "\\YY": "\\tilde{\\mathbf{Y}}",
      "\\ZZ": "\\tilde{\\mathbf{Z}}",

      "\\cB": "\\mathcal{B}",
      "\\cC": "\\mathcal{C}",
      "\\cD": "\\mathcal{D}",
      "\\cE": "\\mathcal{E}",
      "\\cF": "\\mathcal{F}",
      "\\cN": "\\mathcal{N}",
      "\\cR": "\\mathcal{R}",
      "\\cS": "\\mathcal{S}",
      "\\cT": "\\mathcal{T}",
      "\\cV": "\\mathcal{V}",
      "\\cX": "\\mathcal{X}",
      "\\cY": "\\mathcal{Y}",
      "\\cZ": "\\mathcal{Z}",

      "\\gam": "\\gamma",
      "\\lam": "\\lambda",
      "\\Lam": "\\Lambda",
      "\\eps": "\\epsilon",
      "\\vep": "\\varepsilon",
      "\\ba": "\\boldsymbol{\\alpha}",
      "\\bb": "\\boldsymbol{\\beta}",
      "\\bd": "\\boldsymbol{\\delta}",
      "\\be": "\\boldsymbol{\\eta}",
      "\\bep": "\\boldsymbol{\\epsilon}",
      "\\bl": "\\boldsymbol{\\lambda}",
      "\\bg": "\\boldsymbol{\\gamma}",
      "\\bG": "\\boldsymbol{\\Gamma}",
      "\\bL": "\\boldsymbol{\\Lambda}",
      "\\bm": "\\boldsymbol{\\mu}",
      "\\bp": "\\boldsymbol{\\pi}",
      "\\bpsi": "\\boldsymbol{\\psi}",
      "\\bPsi": "\\boldsymbol{\\Psi}",
      "\\bS": "\\boldsymbol{\\Sigma}",
      "\\bvep": "\\boldsymbol{\\varepsilon}",
      "\\bt": "\\boldsymbol{\\theta}",
      "\\bT": "\\boldsymbol{\\Theta}",
      "\\btau": "\\boldsymbol{\\tau}",
      
      "\\real": "\\mathbb{R}",
      "\\Pr": "\\mathbb{P}",
      "\\Ex": "\\mathbb{E}",
      "\\Var": "\\mathbb{V}",
      "\\dx": "\\,dx",

      "\\argmax": "\\mathop{\\mathrm{arg\\,max}}\\limits",
      "\\argmin": "\\mathop{\\mathrm{arg\\,min}}\\limits",
      "\\one": "\\mathbf{1}",
      "\\zero": "\\mathbf{0}",
      "\\intii": "\\int_{-\\infty}^{\\infty}",
      "\\ind": "\\perp\\!\\!\\!\\perp",
      "\\IID": "\\overset{\\scriptscriptstyle \\ind}{\\sim}",

      "\\cov": "\\textrm{Cov}",
      "\\dom": "\\textrm{dom}",
      "\\Exp": "\\textrm{Exp}",
      "\\Norm": "\\textrm{N}",
      "\\OR": "\\textrm{OR}",
      "\\Pois": "\\textrm{Pois}",
      "\\prox": "\\textrm{prox}",
      "\\rank": "\\textrm{rank}",
      "\\RR": "\\textrm{RR}",
      "\\RSS": "\\textrm{RSS}",
      "\\sign": "\\textrm{sign}",
      "\\SE": "\\textrm{SE}",
      "\\trace": "\\textrm{tr}",
      "\\Unif": "\\textrm{Unif}",

      "\\inD": "\\overset{\\text{d}}{\\longrightarrow}", 
      "\\inP": "\\overset{\\text{p}}{\\longrightarrow}",
      "\\inAS": "\\overset{\\textrm{as}\\,}{\\longrightarrow}",
      "\\inQM": "\\overset{\\textnormal{qm}\\,}{\\longrightarrow}",
      "\\adist": "\\overset{\\text{.}}{\\sim}",
      "\\SD": "\\textrm{SD}",
      "\\KL": "\\textrm{KL}",
      "\\CV": "\\textrm{CV}",
      "\\fI": "\\mathscr{I}",
      "\\oI": "\\mathcal{I}",
      "\\iid": "\\overset{\\text{iid}}{\\sim}",

      "\\Tr": "^{\\scriptscriptstyle\\top}",
      "\\Tri": "^{-\\scriptscriptstyle\\top}",
      "\\inprod": ["\\langle #1, #2 \\rangle", 2],
      "\\pf": ["\\frac{\\partial #1}{\\partial #2}", 2],
      "\\star": "^{\\scriptscriptstyle\\ast}",

      "\\norm": ["\\lVert #1 \\rVert", 1],
      "\\abs": ["\\left\\lvert #1 \\right\\rvert", 1],
      "\\given": "\\,\\vert\\,",
      "\\gl": "\\prec",
      "\\gle": "\\preceq",
      "\\gg": "\\succ",
      "\\gge": "\\succeq",
      "\\qed": "\\quad \\blacksquare"
    }
  });
});
